include:
  - '/CI-CD/variables.yml'
  - '/CI-CD/utils.yml'
  - '/CI-CD/workflows.yml'
  - '/CI-CD/version.yml'
  - '/CI-CD/build.yml'
  - '/CI-CD/deploy.yml'

stages:
  - test
  - version
  - build
  - deploy
