apiVersion: batch/v1
kind: CronJob
metadata:
  name: jupyterhub-idle-cms
  namespace: $K8S_NAMESPACE
  labels:
    app: jupyterhub
    component: idle-cms
spec:
  schedule: "*/5 * * * *"               # Каждые 5 минут
  concurrencyPolicy: Forbid             # Только один экземпляр
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600        # Максимум 10 минут на работу
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: default   # Можно оставить default, если у него есть доступ к Vault
          volumes:
            - name: vault-inject
              emptyDir: { }
          initContainers:
            - name: vault-init
              image: harbor.k8s.cmslabs.ru/svc_cms_labs/images/vault-inject:latest
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
              args:
                - "--path=hub"
                - "--output=/var/run/secrets/app"
                - "--formats=json"
              volumeMounts:
                - name: vault-inject
                  mountPath: "/var/run/secrets/app"
                  readOnly: false
          containers:
            - name: idle-cms
              image: "harbor.k8s.cmslabs.ru/svc_jupyter/k8s-hub/${DOCKER_PATH_BRANCH}:${VERSION}"
              imagePullPolicy: Always
              command:
                - python
              args:
                - "-m"
                - "cmsspawner.idle"
              volumeMounts:
                - name: vault-inject
                  mountPath: "/var/run/secrets/app"
                  readOnly: true
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ "ALL" ]
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  cpu: "300m"
                  memory: "100Mi"
                limits:
                  cpu: "500m"
                  memory: "250Mi"