hub:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  variables:
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 10Gi
  needs:
    - version
  script:
    - VERSION="$(cat ./VERSION)"
    - cd backend
    - echo "Building Docker image..."
    - buildah bud --no-cache -t $HUB_CI_IMAGE:$VERSION -f hub.dockerfile .
    - echo "Pushing Docker image to GitLab Registry..."
    - buildah push $HUB_CI_IMAGE:$VERSION
    - buildah push $HUB_CI_IMAGE:latest
    - echo "Deploying application..."