hub:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  variables:
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 10Gi
  needs:
    - version
  script:
    - VERSION="$(cat ./VERSION)"
    - echo "Building Docker image..."
    - buildah bud --no-cache -t $HUB_CI_IMAGE:$VERSION -t $HUB_CI_IMAGE:latest -f hub.dockerfile .
    - echo "Pushing Docker image to GitLab Registry..."
    - buildah push $HUB_CI_IMAGE:$VERSION
    - buildah push $HUB_CI_IMAGE:latest
    - echo "Deploying application..."

notebook:
  stage: build
  extends:
    - .registry_login
    - .releases-branch
  image: ${DOCKER_IMAGE}
  variables:
    KUBERNETES_CPU_LIMIT: 4
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_HELPER_MEMORY_LIMIT: 4Gi
    KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 20Gi
  needs:
    - version
  script:
    - VERSION="$(cat ./VERSION)"
    - echo "Building Docker image..."
    - buildah bud --no-cache -t $NOTEBOOK_CI_IMAGE:$VERSION -t $NOTEBOOK_CI_IMAGE:latest -f notebook.dockerfile .
    - echo "Pushing Docker image to GitLab Registry..."
    - buildah push $NOTEBOOK_CI_IMAGE:$VERSION
    - buildah push $NOTEBOOK_CI_IMAGE:latest
    - echo "Deploying application..."